const tags = [
  { title: 'Xuzhou' },
  { title: 'Action figure' },
  { title: 'Canada' },
  { title: 'Mogadishu' },
  { title: 'American flag rugby' },
  { title: 'Foshan' },
  { title: 'flax' },
  { title: 'Mumbai' },
  { title: 'moss-green' },
  { title: 'Aggressive inline skating' },
  { title: 'Albania' },
  { title: 'Aqua-lung' },
  { title: 'Lyon' },
  { title: 'North Macedonia' },
  { title: 'Gaziantep' },
  { title: 'azure' },
  { title: 'Barrel racing' },
  { title: 'Xiamen' },
  { title: 'Kathmandu' },
  { title: 'Backpacking' },
  { title: 'goldenrod' },
  { title: 'Spain' },
  { title: 'Amateur geology' },
  { title: 'Snowboarding' },
  { title: 'Skiing' },
  { title: 'Hanoi' },
  { title: 'Honduras' },
  { title: 'Xiangyang' },
  { title: 'Kanpur' },
  { title: 'Niger' },
  { title: 'Hungary' },
  { title: 'Animal fancy' },
  { title: 'Auto Race' },
  { title: 'Lubumbashi' },
  { title: 'Matola' },
  { title: 'Australian football' },
  { title: 'Madrid' },
  { title: 'Aizkolaritza' },
  { title: 'Archery' },
  { title: 'Indonesia' },
  { title: 'American handball' },
  { title: 'Baseball pocket billiards' },
  { title: 'malachite' },
  { title: 'Vadodara' },
  { title: 'El Salvador' },
  { title: 'Auckland' },
  { title: 'Peru' },
  { title: 'Jodhpur' },
  { title: 'Zambia' },
  { title: 'Tangerang' },
  { title: 'aqua' },
  { title: 'Syria' },
  { title: 'Ahmedabad' },
  { title: 'Kuwait' },
  { title: 'Air hockey' },
  { title: 'jade' },
  { title: 'Munich' },
  { title: 'chocolate' },
  { title: 'han-purple' },
  { title: 'Atlatl' },
  { title: 'Air sports' },
  { title: 'Kano' },
  { title: 'Ulaanbaatar' },
  { title: 'myrtle' },
  { title: 'Ba game' },
  { title: 'Dakar' },
  { title: 'Vancouver' },
  { title: 'magenta' },
  { title: 'Antiquing' },
  { title: 'chartreuse' },
  { title: 'charcoal' },
  { title: 'coral' },
  { title: 'Hyderabad' },
  { title: 'Minsk' },
  { title: 'Basketball' },
  { title: 'Houston' },
  { title: 'olive' },
  { title: 'Zhongshan' },
  { title: 'Lisbon' },
  { title: 'Chicago' },
  { title: 'lilac' },
  { title: 'lemon' },
  { title: 'bondi-blue' },
  { title: 'Dubai' },
  { title: 'Azerbaijan' },
  { title: 'Guinea-Bissau' },
  { title: 'Ankara' },
  { title: 'carmine' },
  { title: 'Australia' },
  { title: 'Thrissur' },
  { title: 'Shantou' },
  { title: 'Aid climbing' },
  { title: 'Wenzhou' },
  { title: 'Axe throwing' },
  { title: 'Trinidad and Tobago' },
  { title: 'Khartoum' },
  { title: 'blue-violet' },
  { title: 'Madurai' },
  { title: 'Vietnam' },
  { title: 'Philadelphia' },
  { title: 'magnolia' },
  { title: 'denim' },
  { title: 'Bat-and-ball games' },
  { title: 'BMX' },
  { title: 'title' },
  { title: 'Cameroon' },
  { title: 'lime' },
  { title: 'ochre' },
  { title: 'caput-mortuum' },
  { title: 'Kabul' },
  { title: 'amaranth' },
  { title: 'Auto audiophilia' },
  { title: 'Airsoft' },
  { title: 'Myanmar' },
  { title: 'Sweden' },
  { title: 'Onitsha' },
  { title: 'Abseiling' },
  { title: 'hollywood-cerise' },
  { title: 'orange' },
  { title: 'harlequin' },
  { title: 'Sri Lanka' },
  { title: 'Aquathlon' },
  { title: 'camouflage-green' },
  { title: 'Balkline and straight rail' },
  { title: 'Srinagar' },
  { title: 'buff' },
  { title: 'Bat and trap' },
  { title: 'Jilin' },
  { title: 'Datong' },
  { title: 'lemon-chiffon' },
  { title: 'brown' },
  { title: 'Baseball' },
  { title: 'Peshawar' },
  { title: 'Dongguan' },
  { title: 'cobalt' },
  { title: 'Zhuhai' },
  { title: '3D printing' },
  { title: 'Egypt' },
  { title: 'Haerbin' },
  { title: 'lawn-green' },
  { title: 'auburn' },
  { title: 'Kinshasa' },
  { title: 'Anshan' },
  { title: 'gold' },
  { title: 'Bandy' },
  { title: 'ivory' },
  { title: 'Tianjin' },
  { title: 'Esfahan' },
  { title: 'Visakhapatnam' },
  { title: 'Auto racing' },
  { title: 'Aerobatics' },
  { title: 'lavender' },
  { title: 'Bar billiards' },
  { title: 'Croatia' },
  { title: 'Beach Volleyball' },
  { title: 'cherry-blossom-pink' },
  { title: 'corn' },
  { title: 'brass' },
  { title: 'BASE jumping' },
  { title: 'Baguazhang' },
  { title: 'Aviation' },
  { title: 'Sydney' },
  { title: 'Ho Chi Minh City' },
  { title: 'Austria' },
  { title: 'Panama' },
  { title: 'Association football' },
  { title: 'Brazzaville' },
  { title: 'Quito' },
  { title: 'Daegu' },
  { title: 'Artistic gymnastics' },
  { title: 'papaya-whip' },
  { title: 'grey' },
  { title: 'Alpine skiing' },
  { title: 'Qingdao' },
  { title: 'Yangzhou' },
  { title: 'Casablanca' },
  { title: 'Uzbekistan' },
  { title: 'Sapporo' },
  { title: 'Belem' },
  { title: 'olivine' },
  { title: 'Huaian' },
  { title: 'Dalian' },
  { title: 'fern-green' },
  { title: 'Kuwait City' },
  { title: 'Almaty' },
  { title: 'Green' },
  { title: 'Skating' },
  { title: 'Yantai' },
  { title: 'Athens' },
  { title: 'Sao Paulo' },
  { title: 'Aleppo' },
  { title: 'Milan' },
  { title: 'Dominican Republic' },
  { title: 'Nashik' },
  { title: 'Ball badminton' },
  { title: 'Baku' },
  { title: 'Philippines' },
  { title: 'Izmir' },
  { title: 'Shiraz' },
  { title: 'Ancient games' },
  { title: 'Bangalore' },
  { title: 'mint-green' },
  { title: 'linen' },
  { title: 'Colombia' },
  { title: 'Caracas' },
  { title: 'Bagatelle' },
  { title: 'cerise' },
  { title: 'Fuzhou Fujian' },
  { title: 'Port-au-Prince' },
  { title: 'Eritrea' },
  { title: 'carrot-orange' },
  { title: 'Red' },
  { title: 'Santa Cruz' },
  { title: 'Rosario' },
  { title: 'beige' },
  { title: 'Bando' },
  { title: 'Israel' },
  { title: 'Suzhou' },
  { title: 'Lianyungang' },
  { title: 'kelly-green' },
  { title: 'Pakistan' },
  { title: 'Ibadan' },
  { title: 'Nanjing' },
  { title: 'Basque pelota' },
  { title: 'Aikido' },
  { title: 'Puerto Rico' },
  { title: 'Monterrey' },
  { title: 'Aquarium' },
  { title: 'Airsofting' },
  { title: 'peach' },
  { title: 'Liberia' },
  { title: 'cardinal' },
  { title: 'Toluca de Lerdo' },
  { title: 'Baton Twirling' },
  { title: 'office-green' },
  { title: 'Glasgow' },
  { title: 'Valencia' },
  { title: 'ecru' },
  { title: 'Anyang' },
  { title: 'Cape Town' },
  { title: 'Bolivia' },
  { title: 'Belo Horizonte' },
  { title: 'firebrick' },
  { title: 'Arts' },
  { title: 'Cordoba' },
  { title: 'Lagos' },
  { title: 'Guinea' },
  { title: 'Djibouti' },
  { title: 'gamboge' },
  { title: 'Goiania' },
  { title: 'Malappuram' },
  { title: 'Arena football' },
  { title: 'Argentina' },
  { title: 'Sendai' },
  { title: 'Qatar' },
  { title: 'amethyst' },
  { title: 'Puebla' },
  { title: 'Acting' },
  { title: 'Burkina Faso' },
  { title: 'Weifang' },
  { title: 'Artistic cycling' },
  { title: 'Jiangmen' },
  { title: 'Balance beam' },
  { title: 'heliotrope' },
  { title: 'apricot' },
  { title: 'Lome' },
  { title: 'Astrology' },
  { title: 'navajo-white' },
  { title: 'eggplant' },
  { title: 'Astronomy' },
  { title: 'Ouagadougou' },
  { title: 'Thailand' },
  { title: 'Kampala' },
  { title: 'Latvia' },
  { title: 'Recife' },
  { title: 'navy-blue' },
  { title: 'Multan' },
  { title: 'Banger racing' },
  { title: 'Cuba' },
  { title: 'London' },
  { title: 'Beijing' },
  { title: 'Aeromodeling' },
  { title: 'Vijayawada' },
  { title: 'fuchsia' },
  { title: 'Chengdu' },
  { title: 'Ecuador' },
  { title: 'cyan' },
  { title: 'french-rose' },
  { title: 'indigo' },
  { title: 'Arm wrestling' },
  { title: 'Brisbane' },
  { title: 'Aircraft Spotting' },
  { title: 'American snooker' },
  { title: 'Blue' },
  { title: 'cream' },
  { title: 'Montevideo' },
  { title: 'emerald' },
  { title: 'Air racing' },
  { title: 'Bank pool' },
  { title: 'Shizuoka' },
  { title: 'Sudan' },
  { title: 'Gujranwala' },
  { title: 'Australian handball' },
  { title: 'Angling' },
  { title: 'Abuja' },
  { title: 'Aurangabad' },
  { title: 'New York City' },
  { title: 'Cairo' },
  { title: 'khaki' },
  { title: 'Swimming' },
  { title: 'Incheon' },
  { title: 'Karachi' },
  { title: 'orchid' },
  { title: 'Ball' },
  { title: 'Ethiopia' },
  { title: 'Adventure racing' },
  { title: 'Bucharest' },
  { title: 'asparagus' },
  { title: 'Kyrgyzstan' },
  { title: 'Baoding' },
  { title: 'Rome' },
  { title: 'N-Djamena' },
  { title: 'midnight-blue' },
  { title: 'dandelion' },
  { title: 'Birmingham' },
  { title: 'Jaipur' },
  { title: 'Pyongyang' },
  { title: 'misty-rose' },
  { title: 'celadon' },
  { title: 'alizarin' },
  { title: 'Damascus' },
  { title: 'Basque rural sports' },
  { title: 'Tijuana' },
  { title: 'cornflower' },
  { title: 'Beirut' },
  { title: 'maroon' },
  { title: 'Santo Domingo' },
  { title: 'Kannur' },
  { title: 'Jamaica' },
  { title: 'Mashhad' },
  { title: 'Art collecting' },
  { title: 'Backstroke' },
  { title: 'Morocco' },
  { title: 'Algiers' },
  { title: 'Ukraine' },
  { title: 'Varanasi' },
  { title: 'Jamshedpur' },
  { title: 'Panama City' },
  { title: 'Depok' },
  { title: 'forest-green' },
  { title: 'Sierra Leone' },
  { title: 'Adana' },
  { title: 'Autocross' },
  { title: 'Cambodia' },
  { title: 'Palestine' },
  { title: 'Johannesburg' },
  { title: 'Lahore' },
  { title: 'mustard' },
  { title: 'New Zealand' },
  { title: 'Amateur wrestling' },
  { title: 'Republic of the Congo' },
  { title: 'champagne' },
  { title: 'Baotou' },
  { title: 'Ball hockey' },
  { title: 'American football' },
  { title: 'Ekurhuleni' },
  { title: 'Denmark' },
  { title: 'cinnabar' },
  { title: 'bistre' },
  { title: 'Battle gaming' },
  { title: 'amber' },
  { title: 'burgundy' },
  { title: 'Barcelona' },
  { title: 'falu-red' },
  { title: 'Maracaibo' },
  { title: 'bronze' },
  { title: 'lime-green' },
  { title: 'Uganda' },
  { title: 'Turin' },
  { title: 'Turkey' },
  { title: 'Mali' },
  { title: 'Baghdad' },
  { title: 'Georgia' },
  { title: 'Amman' },
  { title: 'Burundi' },
  { title: 'crimson' },
  { title: 'cinnamon' },
  { title: 'Bartitsu' },
  { title: 'black' },
  { title: 'Naples' },
  { title: 'Australian rules football' },
  { title: 'Backgammon' },
  { title: 'Davao City' },
  { title: 'Tanzania' },
  { title: 'Animals/pets/dogs' },
  { title: 'Battōjutsu' },
  { title: 'Surfing' },
  { title: 'Nantong' },
  { title: 'Artistic billiards' },
  { title: 'Amateur Astronomy' }
]
