'use strict';

module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert('Tags', [
      { title: 'Xuzhou' },
      { title: 'Action figure' },
      { title: 'Canada' },
      { title: 'Mogadishu' },
      { title: 'American flag rugby' },
      { title: 'Foshan' },
      { title: 'flax' },
      { title: 'Mumbai' },
      { title: 'moss-green' },
      { title: 'Aggressive inline skating' },
      { title: 'Albania' },
      { title: 'Aqua-lung' },
      { title: 'Lyon' },
      { title: 'North Macedonia' },
      { title: 'Gaziantep' },
      { title: 'azure' },
      { title: 'Barrel racing' },
      { title: 'Xiamen' },
      { title: 'Kathmandu' },
      { title: 'Backpacking' },
      { title: 'goldenrod' },
      { title: 'Spain' },
      { title: 'Amateur geology' },
      { title: 'Snowboarding' },
      { title: 'Skiing' },
      { title: 'Hanoi' },
      { title: 'Honduras' },
      { title: 'Xiangyang' },
      { title: 'Kanpur' },
      { title: 'Niger' },
      { title: 'Hungary' },
      { title: 'Animal fancy' },
      { title: 'Auto Race' },
      { title: 'Lubumbashi' },
      { title: 'Matola' },
      { title: 'Australian football' },
      { title: 'Madrid' },
      { title: 'Aizkolaritza' },
      { title: 'Archery' },
      { title: 'Indonesia' },
      { title: 'American handball' },
      { title: 'Baseball pocket billiards' },
      { title: 'malachite' },
      { title: 'Vadodara' },
      { title: 'El Salvador' },
      { title: 'Auckland' },
      { title: 'Peru' },
      { title: 'Jodhpur' },
      { title: 'Zambia' },
      { title: 'Tangerang' },
      { title: 'aqua' },
      { title: 'Syria' },
      { title: 'Ahmedabad' },
      { title: 'Kuwait' },
      { title: 'Air hockey' },
      { title: 'jade' },
      { title: 'Munich' },
      { title: 'chocolate' },
      { title: 'han-purple' },
      { title: 'Atlatl' },
      { title: 'Air sports' },
      { title: 'Kano' },
      { title: 'Ulaanbaatar' },
      { title: 'myrtle' },
      { title: 'Ba game' },
      { title: 'Dakar' },
      { title: 'Vancouver' },
      { title: 'magenta' },
      { title: 'Antiquing' },
      { title: 'chartreuse' },
      { title: 'charcoal' },
      { title: 'coral' },
      { title: 'Hyderabad' },
      { title: 'Minsk' },
      { title: 'Basketball' },
      { title: 'Houston' },
      { title: 'olive' },
      { title: 'Zhongshan' },
      { title: 'Lisbon' },
      { title: 'Chicago' },
      { title: 'lilac' },
      { title: 'lemon' },
      { title: 'bondi-blue' },
      { title: 'Dubai' },
      { title: 'Azerbaijan' },
      { title: 'Guinea-Bissau' },
      { title: 'Ankara' },
      { title: 'carmine' },
      { title: 'Australia' },
      { title: 'Thrissur' },
      { title: 'Shantou' },
      { title: 'Aid climbing' },
      { title: 'Wenzhou' },
      { title: 'Axe throwing' },
      { title: 'Trinidad and Tobago' },
      { title: 'Khartoum' },
      { title: 'blue-violet' },
      { title: 'Madurai' },
      { title: 'Vietnam' },
      { title: 'Philadelphia' },
      { title: 'magnolia' },
      { title: 'denim' },
      { title: 'Bat-and-ball games' },
      { title: 'BMX' },
      { title: 'title' },
      { title: 'Cameroon' },
      { title: 'lime' },
      { title: 'ochre' },
      { title: 'caput-mortuum' },
      { title: 'Kabul' },
      { title: 'amaranth' },
      { title: 'Auto audiophilia' },
      { title: 'Airsoft' },
      { title: 'Myanmar' },
      { title: 'Sweden' },
      { title: 'Onitsha' },
      { title: 'Abseiling' },
      { title: 'hollywood-cerise' },
      { title: 'orange' },
      { title: 'harlequin' },
      { title: 'Sri Lanka' },
      { title: 'Aquathlon' },
      { title: 'camouflage-green' },
      { title: 'Balkline and straight rail' },
      { title: 'Srinagar' },
      { title: 'buff' },
      { title: 'Bat and trap' },
      { title: 'Jilin' },
      { title: 'Datong' },
      { title: 'lemon-chiffon' },
      { title: 'brown' },
      { title: 'Baseball' },
      { title: 'Peshawar' },
      { title: 'Dongguan' },
      { title: 'cobalt' },
      { title: 'Zhuhai' },
      { title: '3D printing' },
      { title: 'Egypt' },
      { title: 'Haerbin' },
      { title: 'lawn-green' },
      { title: 'auburn' },
      { title: 'Kinshasa' },
      { title: 'Anshan' },
      { title: 'gold' },
      { title: 'Bandy' },
      { title: 'ivory' },
      { title: 'Tianjin' },
      { title: 'Esfahan' },
      { title: 'Visakhapatnam' },
      { title: 'Auto racing' },
      { title: 'Aerobatics' },
      { title: 'lavender' },
      { title: 'Bar billiards' },
      { title: 'Croatia' },
      { title: 'Beach Volleyball' },
      { title: 'cherry-blossom-pink' },
      { title: 'corn' },
      { title: 'brass' },
      { title: 'BASE jumping' },
      { title: 'Baguazhang' },
      { title: 'Aviation' },
      { title: 'Sydney' },
      { title: 'Ho Chi Minh City' },
      { title: 'Austria' },
      { title: 'Panama' },
      { title: 'Association football' },
      { title: 'Brazzaville' },
      { title: 'Quito' },
      { title: 'Daegu' },
      { title: 'Artistic gymnastics' },
      { title: 'papaya-whip' },
      { title: 'grey' },
      { title: 'Alpine skiing' },
      { title: 'Qingdao' },
      { title: 'Yangzhou' },
      { title: 'Casablanca' },
      { title: 'Uzbekistan' },
      { title: 'Sapporo' },
      { title: 'Belem' },
      { title: 'olivine' },
      { title: 'Huaian' },
      { title: 'Dalian' },
      { title: 'fern-green' },
      { title: 'Kuwait City' },
      { title: 'Almaty' },
      { title: 'Green' },
      { title: 'Skating' },
      { title: 'Yantai' },
      { title: 'Athens' },
      { title: 'Sao Paulo' },
      { title: 'Aleppo' },
      { title: 'Milan' },
      { title: 'Dominican Republic' },
      { title: 'Nashik' },
      { title: 'Ball badminton' },
      { title: 'Baku' },
      { title: 'Philippines' },
      { title: 'Izmir' },
      { title: 'Shiraz' },
      { title: 'Ancient games' },
      { title: 'Bangalore' },
      { title: 'mint-green' },
      { title: 'linen' },
      { title: 'Colombia' },
      { title: 'Caracas' },
      { title: 'Bagatelle' },
      { title: 'cerise' },
      { title: 'Fuzhou Fujian' },
      { title: 'Port-au-Prince' },
      { title: 'Eritrea' },
      { title: 'carrot-orange' },
      { title: 'Red' },
      { title: 'Santa Cruz' },
      { title: 'Rosario' },
      { title: 'beige' },
      { title: 'Bando' },
      { title: 'Israel' },
      { title: 'Suzhou' },
      { title: 'Lianyungang' },
      { title: 'kelly-green' },
      { title: 'Pakistan' },
      { title: 'Ibadan' },
      { title: 'Nanjing' },
      { title: 'Basque pelota' },
      { title: 'Aikido' },
      { title: 'Puerto Rico' },
      { title: 'Monterrey' },
      { title: 'Aquarium' },
      { title: 'Airsofting' },
      { title: 'peach' },
      { title: 'Liberia' },
      { title: 'cardinal' },
      { title: 'Toluca de Lerdo' },
      { title: 'Baton Twirling' },
      { title: 'office-green' },
      { title: 'Glasgow' },
      { title: 'Valencia' },
      { title: 'ecru' },
      { title: 'Anyang' },
      { title: 'Cape Town' },
      { title: 'Bolivia' },
      { title: 'Belo Horizonte' },
      { title: 'firebrick' },
      { title: 'Arts' },
      { title: 'Cordoba' },
      { title: 'Lagos' },
      { title: 'Guinea' },
      { title: 'Djibouti' },
      { title: 'gamboge' },
      { title: 'Goiania' },
      { title: 'Malappuram' },
      { title: 'Arena football' },
      { title: 'Argentina' },
      { title: 'Sendai' },
      { title: 'Qatar' },
      { title: 'amethyst' },
      { title: 'Puebla' },
      { title: 'Acting' },
      { title: 'Burkina Faso' },
      { title: 'Weifang' },
      { title: 'Artistic cycling' },
      { title: 'Jiangmen' },
      { title: 'Balance beam' },
      { title: 'heliotrope' },
      { title: 'apricot' },
      { title: 'Lome' },
      { title: 'Astrology' },
      { title: 'navajo-white' },
      { title: 'eggplant' },
      { title: 'Astronomy' },
      { title: 'Ouagadougou' },
      { title: 'Thailand' },
      { title: 'Kampala' },
      { title: 'Latvia' },
      { title: 'Recife' },
      { title: 'navy-blue' },
      { title: 'Multan' },
      { title: 'Banger racing' },
      { title: 'Cuba' },
      { title: 'London' },
      { title: 'Beijing' },
      { title: 'Aeromodeling' },
      { title: 'Vijayawada' },
      { title: 'fuchsia' },
      { title: 'Chengdu' },
      { title: 'Ecuador' },
      { title: 'cyan' },
      { title: 'french-rose' },
      { title: 'indigo' },
      { title: 'Arm wrestling' },
      { title: 'Brisbane' },
      { title: 'Aircraft Spotting' },
      { title: 'American snooker' },
      { title: 'Blue' },
      { title: 'cream' },
      { title: 'Montevideo' },
      { title: 'emerald' },
      { title: 'Air racing' },
      { title: 'Bank pool' },
      { title: 'Shizuoka' },
      { title: 'Sudan' }
    ], {})
  },

  down: (queryInterface, Sequelize) => {
    const Op = Sequelize.Op;
    return queryInterface.bulkDelete('Tags', {
      title: { [Op.in]: [
        "Action figure",
        "Canada",
        "Mogadishu",
        "American flag rugby",
        "Foshan",
        "flax",
        "Mumbai",
        "moss-green",
        "Aggressive inline skating",
        "Albania",
        "Aqua-lung",
        "Lyon",
        "North Macedonia",
        "Gaziantep",
        "azure",
        "Barrel racing",
        "Xiamen",
        "Kathmandu",
        "Backpacking",
        "goldenrod",
        "Spain",
        "Amateur geology",
        "Snowboarding",
        "Skiing",
        "Hanoi",
        "Honduras",
        "Xiangyang",
        "Kanpur",
        "Niger",
        "Hungary",
        "Animal fancy",
        "Auto Race",
        "Lubumbashi",
        "Matola",
        "Australian football",
        "Madrid",
        "Aizkolaritza",
        "Archery",
        "Indonesia",
        "American handball",
        "Baseball pocket billiards",
        "malachite",
        "Vadodara",
        "El Salvador",
        "Auckland",
        "Peru",
        "Jodhpur",
        "Zambia",
        "Tangerang",
        "aqua",
        "Syria",
        "Ahmedabad",
        "Kuwait",
        "Air hockey",
        "jade",
        "Munich",
        "chocolate",
        "han-purple",
        "Atlatl",
        "Air sports",
        "Kano",
        "Ulaanbaatar",
        "myrtle",
        "Ba game",
        "Dakar",
        "Vancouver",
        "magenta",
        "Antiquing",
        "chartreuse",
        "charcoal",
        "coral",
        "Hyderabad",
        "Minsk",
        "Basketball",
        "Houston",
        "olive",
        "Zhongshan",
        "Lisbon",
        "Chicago",
        "lilac",
        "lemon",
        "bondi-blue",
        "Dubai",
        "Azerbaijan",
        "Guinea-Bissau",
        "Ankara",
        "carmine",
        "Australia",
        "Thrissur",
        "Shantou",
        "Aid climbing",
        "Wenzhou",
        "Axe throwing",
        "Trinidad and Tobago",
        "Khartoum",
        "blue-violet",
        "Madurai",
        "Vietnam",
        "Philadelphia",
        "aquamarine",
        "magnolia",
        "denim",
        "Bat-and-ball games",
        "BMX",
        "title",
        "Cameroon",
        "lime",
        "ochre",
        "caput-mortuum",
        "Kabul",
        "amaranth",
        "Auto audiophilia",
        "Airsoft",
        "Myanmar",
        "Sweden",
        "Onitsha",
        "Abseiling",
        "hollywood-cerise",
        "orange",
        "harlequin",
        "Sri Lanka",
        "Aquathlon",
        "camouflage-green",
        "Balkline and straight rail",
        "Srinagar",
        "buff",
        "Bat and trap",
        "Jilin",
        "Datong",
        "lemon-chiffon",
        "brown",
        "Baseball",
        "Peshawar",
        "Dongguan",
        "cobalt",
        "Zhuhai",
        "3D printing",
        "Egypt",
        "Haerbin",
        "lawn-green",
        "auburn",
        "Kinshasa",
        "Anshan",
        "gold",
        "Bandy",
        "ivory",
        "Tianjin",
        "Esfahan",
        "Visakhapatnam",
        "Auto racing",
        "Aerobatics",
        "lavender",
        "Bar billiards",
        "Croatia",
        "Beach Volleyball",
        "cherry-blossom-pink",
        "corn",
        "brass",
        "BASE jumping",
        "Baguazhang",
        "Aviation",
        "Sydney",
        "Ho Chi Minh City",
        "Austria",
        "Panama",
        "Association football",
        "Brazzaville",
        "Quito",
        "Daegu",
        "Artistic gymnastics",
        "papaya-whip",
        "grey",
        "Alpine skiing",
        "Qingdao",
        "Yangzhou",
        "Casablanca",
        "Uzbekistan",
        "Sapporo",
        "Belem",
        "olivine",
        "Huaian",
        "Dalian",
        "fern-green",
        "Kuwait City",
        "Almaty",
        "Green",
        "Skating",
        "Yantai",
        "Athens",
        "Sao Paulo",
        "Aleppo",
        "Milan",
        "Dominican Republic",
        "Nashik",
        "Ball badminton",
        "Baku",
        "Philippines",
        "Izmir",
        "Shiraz",
        "Ancient games",
        "Bangalore",
        "mint-green",
        "linen",
        "Colombia",
        "Caracas",
        "Bagatelle",
        "cerise",
        "Fuzhou Fujian",
        "Port-au-Prince",
        "Eritrea",
        "carrot-orange",
        "Red",
        "Santa Cruz",
        "Rosario",
        "beige",
        "Bando",
        "Israel",
        "Suzhou",
        "Lianyungang",
        "kelly-green",
        "Pakistan",
        "Ibadan",
        "Nanjing",
        "Basque pelota",
        "Aikido",
        "Puerto Rico",
        "Monterrey",
        "Aquarium",
        "Airsofting",
        "peach",
        "Liberia",
        "cardinal",
        "Toluca de Lerdo",
        "Baton Twirling",
        "office-green",
        "Glasgow",
        "Valencia",
        "ecru",
        "Anyang",
        "Cape Town",
        "Bolivia",
        "Belo Horizonte",
        "firebrick",
        "Arts",
        "Cordoba",
        "Lagos",
        "Guinea",
        "Djibouti",
        "gamboge",
        "Goiania",
        "Malappuram",
        "Arena football",
        "Argentina",
        "Sendai",
        "Qatar",
        "amethyst",
        "Puebla",
        "Acting",
        "Burkina Faso",
        "Weifang",
        "Artistic cycling",
        "Jiangmen",
        "Balance beam",
        "heliotrope",
        "apricot",
        "Lome",
        "Astrology",
        "navajo-white",
        "eggplant",
        "Astronomy",
        "Ouagadougou",
        "Thailand",
        "Kampala",
        "Latvia",
        "Recife",
        "navy-blue",
        "Multan",
        "Banger racing",
        "Cuba",
        "London",
        "Beijing",
        "Aeromodeling",
        "Vijayawada",
        "fuchsia",
        "Chengdu",
        "Ecuador",
        "cyan",
        "french-rose",
        "indigo",
        "Arm wrestling",
        "Brisbane",
        "Aircraft Spotting",
        "American snooker",
        "Blue",
        "cream",
        "Montevideo",
        "emerald",
        "Air racing",
        "Bank pool",
        "Shizuoka",
        "Sudan"
      ]}
    }, {})
  }
};
